version: '3'   
services:
  mysql:
    image: "mysql:latest"
    container_name: mysqldb
    ports:
     - "3306:3306"
    volumes:
       - ./db-data:/var/lib/mysql
    environment:
       - MYSQL_ROOT_PASSWORD=test
       - MYSQL_DATABASE=strava
    networks:
       mynet:
        aliases:
         - dbserver

  springboot:
      image: "dockerservice/mservices"
      ports:
         - "8080:8080"
         - "8000:8000"
      networks:
        - mynet
      depends_on:
        - mysql


  zookeeper:
     image: wurstmeister/zookeeper
     ports:
       - "2181:2181"
     networks:
        - mynet

  kafka:
    build: kafka-docker
    ports:
     - "9092:9092"    
    environment:
       KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
       KAFKA_CREATE_TOPICS: "test:1:1"
       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
        - mynet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
    db-data:
networks:
    mynet:
    